import {Factor5Scales} from "./types";

export const createBlankScales: IScaleFactory<Factor5Scales> = function (v) {
    return {
        "I": v,
        "I.1": v,
        "I.2": v,
        "I.3": v,
        "I.4": v,
        "I.5": v,
        "II": v,
        "II.1": v,
        "II.2": v,
        "II.3": v,
        "II.4": v,
        "II.5": v,
        "III": v,
        "III.1": v,
        "III.2": v,
        "III.3": v,
        "III.4": v,
        "III.5": v,
        "IV": v,
        "IV.1": v,
        "IV.2": v,
        "IV.3": v,
        "IV.4": v,
        "IV.5": v,
        "V": v,
        "V.1": v,
        "V.2": v,
        "V.3": v,
        "V.4": v,
        "V.5": v,
    };
};
