export type Factor5Scales = {
    "I": number;
    "I.1": number;
    "I.2": number;
    "I.3": number;
    "I.4": number;
    "I.5": number;
    "II": number;
    "II.1": number;
    "II.2": number;
    "II.3": number;
    "II.4": number;
    "II.5": number;
    "III": number;
    "III.1": number;
    "III.2": number;
    "III.3": number;
    "III.4": number;
    "III.5": number;
    "IV": number;
    "IV.1": number;
    "IV.2": number;
    "IV.3": number;
    "IV.4": number;
    "IV.5": number;
    "V": number;
    "V.1": number;
    "V.2": number;
    "V.3": number;
    "V.4": number;
    "V.5": number;
};

export type Factor5Answer = -2 | -1 | 0 | 1 | 2;
